// Cholesky: the policy (tuned per device, estimated for the rest, as QR's,
// the eigensolver's and the SVD's), the routing, and core::cholesky.
#import <Metal/Metal.h>

#include "calibration.h"
#include "estimate.h"
#include "metal_runtime.h"
#include <metal_linalg/core.h>
#include <metal_linalg/device.h>

#include <algorithm>
#include <cstdlib>
#include <string>

namespace metal_linalg {
namespace {

// One row per measured GPU (src/tuned/cholesky.inc, generated by
// tuning/generate_tables.py from every run in docs/results/), the policy's
// fields in order; the estimated rows for the rest, as the other
// decompositions' (estimate.h).
struct TunedEntry {
    const char* device_name;   // exact MTLDevice.name
    unsigned    gpu_cores;
    unsigned    simd_max_n;
    unsigned    blocked_min_n;
    unsigned    blocked_max_batch;
    unsigned    gpu_max_n;
    unsigned    gpu_min_batch_times_n;
    unsigned    gpu_min_batch;
    unsigned    gpu_min_n;
    unsigned    gpu_large_min_n;
    unsigned    gpu_large_max_batch;
    unsigned    calibration;   // kCalibration* (calibration.h); rows without it are current
};

constexpr TunedEntry kTuned[] = {
#include "tuned/cholesky.inc"
    {"", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

struct EstimatedEntry {
    unsigned   small_x100;        // batched kernels' slowdown x 100
    unsigned   large_x100;        // the large-matrix path's slowdown x 100
    unsigned   anchor_cpu_cores;
    TunedEntry row;
};
constexpr EstimatedEntry kEstimated[] = {
#include "tuned/cholesky_estimated.inc"
    {0, 0, 0, {"", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}},
};

void apply(const TunedEntry& e, CholeskyPolicy& p) {
    p.simd_max_n            = e.simd_max_n;
    p.blocked_min_n         = e.blocked_min_n;
    p.blocked_max_batch     = e.blocked_max_batch;
    p.gpu_max_n             = e.gpu_max_n;
    p.gpu_min_batch_times_n = e.gpu_min_batch_times_n;
    p.gpu_min_batch         = e.gpu_min_batch;
    p.gpu_min_n             = e.gpu_min_n;
    p.gpu_large_min_n       = e.gpu_large_min_n;
    p.gpu_large_max_batch   = e.gpu_large_max_batch;
}

struct ResolvedPolicy {
    CholeskyPolicy policy;
    std::string    source;
};

// A non-negative integer from the environment; zero is a valid value.
bool env_value(const char* name, unsigned& out) {
    const char* s = std::getenv(name);
    if (!s || !*s) return false;
    char* end = nullptr;
    const long long v = std::strtoll(s, &end, 10);
    if (end == s || v < 0) return false;
    out = v > 0xFFFFFFFFll ? 0xFFFFFFFFu : (unsigned)v;
    return true;
}

ResolvedPolicy resolve() {
    ResolvedPolicy r;
    @autoreleasepool {
        const std::string name = device_name();
        r.policy.gpu_cores = gpu_core_count();
        bool forced = false;   // METAL_LINALG_ESTIMATE_AS: estimate even a measured GPU
        const detail::EstimateTarget target = detail::estimate_target(&forced);
        for (const auto& e : kTuned) {
            if (forced) break;
            if (e.device_name[0] != '\0' && name == e.device_name && r.policy.gpu_cores == e.gpu_cores) {
                apply(e, r.policy);
                r.source = detail::tuned_source_prefix(e.calibration) + name;
                detail::calibration_notice("Cholesky", e.calibration);
                break;
            }
        }
        if (r.source.empty() && !target.device.empty()) {
            std::string source;
            if (const EstimatedEntry* e = detail::estimated_row(kEstimated, target, source)) {
                apply(e->row, r.policy);
                r.source = source;
                detail::calibration_notice("Cholesky", kUncalibrated);
            }
        }
        if (r.source.empty()) {
            // the CholeskyPolicy defaults
            r.source = "default:untuned-device" + (name.empty() ? "" : " (" + name + ")");
            detail::calibration_notice("Cholesky", kUncalibrated);
        }
    }
    std::string env;
    auto over = [&](const char* name, unsigned& field) {
        if (env_value(name, field)) env += (env.empty() ? "" : ",") + std::string(name);
    };
    over("CHOLESKY_SIMD_MAX_N",            r.policy.simd_max_n);
    over("CHOLESKY_BLOCKED_MIN_N",         r.policy.blocked_min_n);
    over("CHOLESKY_BLOCKED_MAX_BATCH",     r.policy.blocked_max_batch);
    over("CHOLESKY_GPU_MAX_N",             r.policy.gpu_max_n);
    over("CHOLESKY_GPU_MIN_BATCH_TIMES_N", r.policy.gpu_min_batch_times_n);
    over("CHOLESKY_GPU_MIN_BATCH",         r.policy.gpu_min_batch);
    over("CHOLESKY_GPU_MIN_N",             r.policy.gpu_min_n);
    over("CHOLESKY_GPU_LARGE_MIN_N",       r.policy.gpu_large_min_n);
    over("CHOLESKY_GPU_LARGE_MAX_BATCH",   r.policy.gpu_large_max_batch);
    if (!env.empty()) r.source = "env:" + env;
    return r;
}

ResolvedPolicy& state() {
    static ResolvedPolicy s = resolve();
    return s;
}

// The GPU or the CPU, by the policy's rule.
bool uses_gpu(const CholeskyPolicy& p, unsigned n, unsigned batch) {
    if (p.gpu_large_min_n && n >= p.gpu_large_min_n && (!p.gpu_large_max_batch || batch <= p.gpu_large_max_batch))
        return true;
    return n >= p.gpu_min_n && n <= p.gpu_max_n && (uint64_t)batch * n >= p.gpu_min_batch_times_n &&
           batch >= std::max(1u, p.gpu_min_batch);
}

CholeskyBackend gpu_kernel(const CholeskyPolicy& p, unsigned n, unsigned batch) {
    if (n <= std::min(32u, p.simd_max_n)) return CholeskyBackend::simd;
    if (n >= p.blocked_min_n && (!p.blocked_max_batch || batch <= p.blocked_max_batch))
        return CholeskyBackend::blocked;
    return CholeskyBackend::threadgroup;
}

} // namespace

CholeskyPolicy cholesky_policy()        { return state().policy; }
const char*    cholesky_policy_source() { return state().source.c_str(); }

void set_cholesky_policy(const CholeskyPolicy& p) {
    state().policy = p;
    state().source = "user";
}

CholeskyBackend cholesky_gpu_backend(unsigned n, unsigned batch) {
    if (const char* e = std::getenv("CHOLESKY_DEVICE")) {
        const std::string s = e;
        if (s == "simd" && n <= 32) return CholeskyBackend::simd;
        if (s == "threadgroup") return CholeskyBackend::threadgroup;
        if (s == "blocked") return CholeskyBackend::blocked;
    }
    return gpu_kernel(state().policy, n, batch);
}

CholeskyBackend cholesky_backend(unsigned n, unsigned batch) {
    if (const char* e = std::getenv("CHOLESKY_DEVICE")) {
        const std::string s = e;
        if (s == "cpu") return CholeskyBackend::cpu;
        if (s == "gpu" || s == "simd" || s == "threadgroup" || s == "blocked") return cholesky_gpu_backend(n, batch);
    }
    return uses_gpu(state().policy, n, batch) ? cholesky_gpu_backend(n, batch) : CholeskyBackend::cpu;
}

void core::cholesky(const Matrices& a, bool upper, float* l, uint32_t* info) {
    if (a.rows != a.cols)
        throw std::invalid_argument("[cholesky] The matrices must be square, got " + std::to_string(a.rows) + "x" +
                                    std::to_string(a.cols) + ".");
    if (a.cols == 0 || a.batch == 0) return;
    switch (cholesky_backend(a.cols, a.batch)) {
        case CholeskyBackend::cpu:         core::detail::cholesky_cpu(a, upper, l, info); return;
        case CholeskyBackend::simd:        core::detail::cholesky_simd(a, upper, l, info); return;
        case CholeskyBackend::threadgroup: core::detail::cholesky_threadgroup(a, upper, l, info); return;
        case CholeskyBackend::blocked:     core::detail::cholesky_blocked(a, upper, l, info); return;
    }
}

} // namespace metal_linalg
