// LU: the policy (tuned per device, estimated for the rest, as the other
// decompositions'), the routing, and core::lu_factor, core::solve, core::inv.
#import <Metal/Metal.h>

#include "calibration.h"
#include "estimate.h"
#include "metal_runtime.h"
#include <metal_linalg/core.h>
#include <metal_linalg/device.h>

#include <algorithm>
#include <cstdlib>
#include <string>

namespace metal_linalg {
namespace {

// One row per measured GPU (src/tuned/lu.inc, generated by
// tuning/generate_tables.py from every run in docs/results/), the policy's
// fields in order; the estimated rows for the rest, as the other
// decompositions' (estimate.h).
struct TunedEntry {
    const char* device_name;   // exact MTLDevice.name
    unsigned    gpu_cores;
    unsigned    gpu_min_n;
    unsigned    gpu_max_batch;
    unsigned    gpu_solve_min_rhs;
    unsigned    calibration;   // kCalibration* (calibration.h); rows without it are current
};

constexpr TunedEntry kTuned[] = {
#include "tuned/lu.inc"
    {"", 0, 0, 0, 0, 0},
};

struct EstimatedEntry {
    unsigned   small_x100;        // batched kernels' slowdown x 100
    unsigned   large_x100;        // the large-matrix path's slowdown x 100
    unsigned   anchor_cpu_cores;
    TunedEntry row;
};
constexpr EstimatedEntry kEstimated[] = {
#include "tuned/lu_estimated.inc"
    {0, 0, 0, {"", 0, 0, 0, 0, 0}},
};

void apply(const TunedEntry& e, LuPolicy& p) {
    p.gpu_min_n         = e.gpu_min_n;
    p.gpu_max_batch     = e.gpu_max_batch;
    p.gpu_solve_min_rhs = e.gpu_solve_min_rhs;
}

struct ResolvedPolicy {
    LuPolicy policy;
    std::string    source;
};

// A non-negative integer from the environment; zero is a valid value.
bool env_value(const char* name, unsigned& out) {
    const char* s = std::getenv(name);
    if (!s || !*s) return false;
    char* end = nullptr;
    const long long v = std::strtoll(s, &end, 10);
    if (end == s || v < 0) return false;
    out = v > 0xFFFFFFFFll ? 0xFFFFFFFFu : (unsigned)v;
    return true;
}

ResolvedPolicy resolve() {
    ResolvedPolicy r;
    @autoreleasepool {
        const std::string name = device_name();
        r.policy.gpu_cores = gpu_core_count();
        bool forced = false;   // METAL_LINALG_ESTIMATE_AS: estimate even a measured GPU
        const detail::EstimateTarget target = detail::estimate_target(&forced);
        for (const auto& e : kTuned) {
            if (forced) break;
            if (e.device_name[0] != '\0' && name == e.device_name && r.policy.gpu_cores == e.gpu_cores) {
                apply(e, r.policy);
                r.source = detail::tuned_source_prefix(e.calibration) + name;
                detail::calibration_notice("LU", e.calibration);
                break;
            }
        }
        if (r.source.empty() && !target.device.empty()) {
            std::string source;
            if (const EstimatedEntry* e = detail::estimated_row(kEstimated, target, source)) {
                apply(e->row, r.policy);
                r.source = source;
                detail::calibration_notice("LU", kUncalibrated);
            }
        }
        if (r.source.empty()) {
            // the LuPolicy defaults
            r.source = "default:untuned-device" + (name.empty() ? "" : " (" + name + ")");
            detail::calibration_notice("LU", kUncalibrated);
        }
    }
    std::string env;
    auto over = [&](const char* name, unsigned& field) {
        if (env_value(name, field)) env += (env.empty() ? "" : ",") + std::string(name);
    };
    over("LU_GPU_MIN_N",         r.policy.gpu_min_n);
    over("LU_GPU_MAX_BATCH",     r.policy.gpu_max_batch);
    over("LU_GPU_SOLVE_MIN_RHS", r.policy.gpu_solve_min_rhs);
    if (!env.empty()) r.source = "env:" + env;
    return r;
}

ResolvedPolicy& state() {
    static ResolvedPolicy s = resolve();
    return s;
}

// The GPU or the CPU, by the policy's rule.
bool uses_gpu(const LuPolicy& p, unsigned n, unsigned batch) {
    return p.gpu_min_n && n >= p.gpu_min_n && (!p.gpu_max_batch || batch <= p.gpu_max_batch);
}

} // namespace

LuPolicy    lu_policy()        { return state().policy; }
const char* lu_policy_source() { return state().source.c_str(); }

void set_lu_policy(const LuPolicy& p) {
    state().policy = p;
    state().source = "user";
}

LuBackend lu_backend(unsigned n, unsigned batch) {
    if (cpu_only()) return LuBackend::cpu;   // this thread's setting (device.h), ahead of LU_DEVICE
    if (const char* e = std::getenv("LU_DEVICE")) {
        const std::string s = e;
        if (s == "cpu") return LuBackend::cpu;
        if (s == "gpu" || s == "blocked") return LuBackend::blocked;
    }
    return uses_gpu(state().policy, n, batch) ? LuBackend::blocked : LuBackend::cpu;
}

namespace {
void require_square(const core::Matrices& a, const char* what) {
    if (a.rows != a.cols)
        throw std::invalid_argument(std::string("[") + what + "] The matrices must be square, got " +
                                    std::to_string(a.rows) + "x" + std::to_string(a.cols) + ".");
}
} // namespace

void core::lu_factor(const Matrices& a, float* lu, uint32_t* pivots, uint32_t* info) {
    require_square(a, "lu_factor");
    if (a.cols == 0 || a.batch == 0) return;
    if (lu_backend(a.cols, a.batch) == LuBackend::blocked) core::detail::lu_factor_blocked(a, lu, pivots, info);
    else core::detail::lu_factor_cpu(a, lu, pivots, info);
}

void core::solve(const Matrices& a, const float* b, uint32_t nrhs, float* x, uint32_t* info) {
    require_square(a, "solve");
    if (lu_backend(a.cols, a.batch) == LuBackend::blocked) core::detail::solve_blocked(a, b, nrhs, x, info);
    else core::detail::solve_cpu(a, b, nrhs, x, info);
}

void core::inv(const Matrices& a, float* x, uint32_t* info) {
    require_square(a, "inv");
    if (a.cols == 0 || a.batch == 0) return;
    if (lu_backend(a.cols, a.batch) == LuBackend::blocked) core::detail::inv_blocked(a, x, info);
    else core::detail::inv_cpu(a, x, info);
}

} // namespace metal_linalg
