// Triangular solve, A X = B with A triangular: the policy (tuned per device,
// estimated for the rest, as the other decompositions'), the routing, both
// backends, and core::solve_triangular.
//
// The CPU path is BLAS's strsm on the row-major matrices as they are, a batch
// spread over every core. The GPU path (blocked) takes one matrix at a time,
// 128 rows of X at a time: X_i = A_ii^-1 B'_i, then B' -= A(rest, i) X_i for
// the rows still to come, two MPS products a block, on the caller's matrices
// in place (row-major blocks of A are what MPS reads, so nothing is
// transposed); the inverses of A's 128 x 128 diagonal blocks are made on the
// CPU (strtri). One 4096 x 4096 with 4096 right-hand sides in about 10 ms on an
// M5 Pro, against 49 for strsm on every core.
#ifndef ACCELERATE_NEW_LAPACK
#define ACCELERATE_NEW_LAPACK
#endif
#import <Metal/Metal.h>
#import <MetalPerformanceShaders/MetalPerformanceShaders.h>
#include <Accelerate/Accelerate.h>

#include "calibration.h"
#include "estimate.h"
#include "metal_runtime.h"
#include "shaders.h"
#include "transpose.h"
#include <metal_linalg/core.h>
#include <metal_linalg/device.h>

#include <algorithm>
#include <cstdlib>
#include <map>
#include <stdexcept>
#include <string>
#include <tuple>
#include <unistd.h>

namespace metal_linalg {
namespace {

// One row per measured GPU (src/tuned/trsm.inc, generated by
// tuning/generate_tables.py from every run in docs/results/), the policy's
// fields in order; the estimated rows for the rest, as the other
// decompositions' (estimate.h).
struct TunedEntry {
    const char* device_name;   // exact MTLDevice.name
    unsigned    gpu_cores;
    unsigned    gpu_min_n;
    unsigned    gpu_min_rhs;
    unsigned    gpu_max_batch;
    unsigned    calibration;   // kCalibration* (calibration.h); rows without it are current
};

constexpr TunedEntry kTuned[] = {
#include "tuned/trsm.inc"
    {"", 0, 0, 0, 0, 0},
};

struct EstimatedEntry {
    unsigned   small_x100;
    unsigned   large_x100;
    unsigned   anchor_cpu_cores;
    TunedEntry row;
};
constexpr EstimatedEntry kEstimated[] = {
#include "tuned/trsm_estimated.inc"
    {0, 0, 0, {"", 0, 0, 0, 0, 0}},
};

void apply(const TunedEntry& e, TrsmPolicy& p) {
    p.gpu_min_n     = e.gpu_min_n;
    p.gpu_min_rhs   = e.gpu_min_rhs;
    p.gpu_max_batch = e.gpu_max_batch;
}

struct ResolvedPolicy {
    TrsmPolicy policy;
    std::string    source;
};

// A non-negative integer from the environment; zero is a valid value.
bool env_value(const char* name, unsigned& out) {
    const char* s = std::getenv(name);
    if (!s || !*s) return false;
    char* end = nullptr;
    const long long v = std::strtoll(s, &end, 10);
    if (end == s || v < 0) return false;
    out = v > 0xFFFFFFFFll ? 0xFFFFFFFFu : (unsigned)v;
    return true;
}

ResolvedPolicy resolve() {
    ResolvedPolicy r;
    @autoreleasepool {
        const std::string name = device_name();
        r.policy.gpu_cores = gpu_core_count();
        bool forced = false;   // METAL_LINALG_ESTIMATE_AS: estimate even a measured GPU
        const detail::EstimateTarget target = detail::estimate_target(&forced);
        for (const auto& e : kTuned) {
            if (forced) break;
            if (e.device_name[0] != '\0' && name == e.device_name && r.policy.gpu_cores == e.gpu_cores) {
                apply(e, r.policy);
                r.source = detail::tuned_source_prefix(e.calibration) + name;
                detail::calibration_notice("triangular solve", e.calibration);
                break;
            }
        }
        if (r.source.empty() && !target.device.empty()) {
            std::string source;
            if (const EstimatedEntry* e = detail::estimated_row(kEstimated, target, source)) {
                apply(e->row, r.policy);
                r.source = source;
                detail::calibration_notice("triangular solve", kUncalibrated);
            }
        }
        if (r.source.empty()) {
            // the TrsmPolicy defaults
            r.source = "default:untuned-device" + (name.empty() ? "" : " (" + name + ")");
            detail::calibration_notice("triangular solve", kUncalibrated);
        }
    }
    std::string env;
    auto over = [&](const char* name, unsigned& field) {
        if (env_value(name, field)) env += (env.empty() ? "" : ",") + std::string(name);
    };
    over("TRSM_GPU_MIN_N",     r.policy.gpu_min_n);
    over("TRSM_GPU_MIN_RHS",   r.policy.gpu_min_rhs);
    over("TRSM_GPU_MAX_BATCH", r.policy.gpu_max_batch);
    if (!env.empty()) r.source = "env:" + env;
    return r;
}

ResolvedPolicy& state() {
    static ResolvedPolicy s = resolve();
    return s;
}

bool uses_gpu(const TrsmPolicy& p, unsigned n, unsigned k, unsigned batch) {
    return p.gpu_min_n && n >= p.gpu_min_n && k >= p.gpu_min_rhs && (!p.gpu_max_batch || batch <= p.gpu_max_batch);
}

void require_square(const core::Matrices& a, const char* what) {
    if (a.rows != a.cols)
        throw std::invalid_argument(std::string("[solve_triangular] ") + what + "the matrices must be square, got " +
                                    std::to_string(a.rows) + "x" + std::to_string(a.cols) + ".");
}

// -----------------------------------------------------------------------------
// The GPU path
// -----------------------------------------------------------------------------

constexpr uint32_t kBlock = 128;

struct Cache {
    detail::MetalRuntime& rt = detail::MetalRuntime::shared(METAL_LINALG_SHADER(LU), "lu");
    id<MTLBuffer> inv = nil, work = nil, out = nil;
    size_t inv_floats = 0, work_floats = 0, out_floats = 0;
    id<MTLBuffer> grow(id<MTLBuffer> __strong& b, size_t& have, size_t want, MTLResourceOptions opt) {
        if (!b || have < want) {
            b = [rt.device newBufferWithLength:std::max<size_t>(16, want * sizeof(float)) options:opt];
            if (!b) throw std::runtime_error("[solve_triangular] could not allocate a GPU workspace");
            have = want;
        }
        return b;
    }
    static Cache& shared() {
        static Cache c;
        return c;
    }
};

MPSMatrixMultiplication* gemm(id<MTLDevice> dev, uint32_t m, uint32_t n, uint32_t k, bool ta, float alpha, float beta) {
    using Key = std::tuple<uint32_t, uint32_t, uint32_t, bool, float, float>;
    thread_local std::map<Key, MPSMatrixMultiplication*> kernels;
    const Key key{m, n, k, ta, alpha, beta};
    auto it = kernels.find(key);
    if (it == kernels.end()) {
        if (kernels.size() >= 4096) kernels.clear();
        it = kernels.emplace(key, [[MPSMatrixMultiplication alloc] initWithDevice:dev transposeLeft:ta transposeRight:NO
                                       resultRows:m resultColumns:n interiorColumns:k alpha:alpha beta:beta]).first;
    }
    return it->second;
}

MPSMatrix* view(id<MTLBuffer> b, size_t off, uint32_t rows, uint32_t cols, uint32_t ld) {
    MPSMatrixDescriptor* d = [MPSMatrixDescriptor matrixDescriptorWithRows:rows columns:cols rowBytes:(size_t)ld * 4
                                                                  dataType:MPSDataTypeFloat32];
    return [[MPSMatrix alloc] initWithBuffer:b offset:off * 4 descriptor:d];
}

} // namespace

namespace core::detail {

void solve_triangular_cpu(const Matrices& a, const float* b, uint32_t nrhs, bool upper, bool unit, float* x) {
    require_square(a, "cpu: ");
    const uint32_t n = a.cols, batch = a.batch;
    if (n == 0 || batch == 0 || nrhs == 0) return;
    const size_t per = (size_t)n * n, bper = (size_t)n * nrhs;
    metal_linalg::detail::lapack_batches(batch, per, [&](uint32_t b0, uint32_t b1) {
        for (uint32_t m = b0; m < b1; ++m) {
            std::copy(b + m * bper, b + (m + 1) * bper, x + m * bper);
            cblas_strsm(CblasRowMajor, CblasLeft, upper ? CblasUpper : CblasLower, CblasNoTrans,
                        unit ? CblasUnit : CblasNonUnit, (__LAPACK_int)n, (__LAPACK_int)nrhs, 1.0f, a.data + m * per,
                        (__LAPACK_int)n, x + m * bper, (__LAPACK_int)nrhs);
        }
    });
}

void solve_triangular_blocked(const Matrices& a, const float* b, uint32_t nrhs, bool upper, bool unit, float* x) {
    require_square(a, "blocked: ");
    const uint32_t n = a.cols, batch = a.batch, k = nrhs;
    if (n == 0 || batch == 0 || k == 0) return;
    metal_linalg::detail::AutoreleasePool pool;
    Cache& c = Cache::shared();
    id<MTLDevice> dev = c.rt.device;
    const size_t per = (size_t)n * n, bper = (size_t)n * k;
    const uint32_t nblocks = (n + kBlock - 1) / kBlock;
    id<MTLBuffer> A = metal_linalg::detail::input_buffer(dev, a);
    id<MTLBuffer> B = metal_linalg::detail::input_buffer(dev, Matrices{b, batch, n, k});
    const bool direct = reinterpret_cast<uintptr_t>(x) % (size_t)getpagesize() == 0;
    id<MTLBuffer> X = direct ? metal_linalg::detail::wrap_host(dev, x, bper * batch)
                             : c.grow(c.out, c.out_floats, bper * batch, MTLResourceStorageModeShared);
    c.grow(c.inv, c.inv_floats, (size_t)nblocks * kBlock * kBlock, MTLResourceStorageModeShared);
    c.grow(c.work, c.work_floats, bper, MTLResourceStorageModePrivate);
    float* inv = static_cast<float*>([c.inv contents]);
    for (uint32_t m = 0; m < batch; ++m) {
        // the diagonal blocks' inverses, column-major (their row-major views
        // are the transposes MPS's transposeLeft undoes)
        const float* am = a.data + m * per;
        metal_linalg::detail::parallel_for(nblocks, [&](size_t blk) {
            const uint32_t i0 = (uint32_t)blk * kBlock, ib = std::min(kBlock, n - i0);
            float* I = inv + blk * kBlock * kBlock;
            for (uint32_t col = 0; col < ib; ++col)
                for (uint32_t r = 0; r < ib; ++r) {
                    const bool in = upper ? r <= col : r >= col;
                    I[(size_t)col * kBlock + r] = r == col && unit ? 1.0f : in ? am[(size_t)(i0 + r) * n + i0 + col] : 0.0f;
                }
            char uplo = upper ? 'U' : 'L', diag = unit ? 'U' : 'N';
            __LAPACK_int lb = (__LAPACK_int)ib, lk = (__LAPACK_int)kBlock, e = 0;
            strtri_(&uplo, &diag, &lb, I, &lk, &e);
        });
        id<MTLCommandBuffer> cmd = [c.rt.queue commandBuffer];
        id<MTLBlitCommandEncoder> blit = [cmd blitCommandEncoder];   // B into the workspace, updated in place
        [blit copyFromBuffer:B sourceOffset:m * bper * 4 toBuffer:c.work destinationOffset:0 size:bper * 4];
        [blit endEncoding];
        for (uint32_t step = 0; step < nblocks; ++step) {
            const uint32_t blk = upper ? nblocks - 1 - step : step, i0 = blk * kBlock, ib = std::min(kBlock, n - i0);
            MPSMatrix* Ii = view(c.inv, (size_t)blk * kBlock * kBlock, ib, ib, kBlock);
            MPSMatrix* Yi = view(c.work, (size_t)i0 * k, ib, k, k);
            MPSMatrix* Xi = view(X, m * bper + (size_t)i0 * k, ib, k, k);
            [gemm(dev, ib, k, ib, true, 1.0f, 0.0f) encodeToCommandBuffer:cmd leftMatrix:Ii rightMatrix:Yi resultMatrix:Xi];
            // the rows still to come: below the block (lower), above it (upper)
            const uint32_t r0 = upper ? 0 : i0 + ib, rows = upper ? i0 : n - i0 - ib;
            if (!rows) continue;
            MPSMatrix* Ar = view(A, m * per + (size_t)r0 * n + i0, rows, ib, n);
            MPSMatrix* Yr = view(c.work, (size_t)r0 * k, rows, k, k);
            [gemm(dev, rows, k, ib, false, -1.0f, 1.0f) encodeToCommandBuffer:cmd leftMatrix:Ar rightMatrix:Xi
                                                                     resultMatrix:Yr];
        }
        [cmd commit];
        [cmd waitUntilCompleted];
        if (cmd.error)
            throw std::runtime_error(std::string("[solve_triangular] GPU error: ") +
                                     cmd.error.localizedDescription.UTF8String);
    }
    if (!direct) metal_linalg::detail::copy_out(static_cast<const float*>([X contents]), x, batch, bper);
}

} // namespace core::detail

TrsmPolicy  trsm_policy()        { return state().policy; }
const char* trsm_policy_source() { return state().source.c_str(); }

void set_trsm_policy(const TrsmPolicy& p) {
    state().policy = p;
    state().source = "user";
}

TrsmBackend trsm_backend(unsigned n, unsigned k, unsigned batch) {
    if (const char* e = std::getenv("TRSM_DEVICE")) {
        const std::string s = e;
        if (s == "cpu") return TrsmBackend::cpu;
        if (s == "gpu" || s == "blocked") return TrsmBackend::blocked;
    }
    return uses_gpu(state().policy, n, k, batch) ? TrsmBackend::blocked : TrsmBackend::cpu;
}

void core::solve_triangular(const Matrices& a, const float* b, uint32_t nrhs, bool upper, bool unit, float* x) {
    require_square(a, "");
    if (trsm_backend(a.cols, nrhs, a.batch) == TrsmBackend::blocked)
        core::detail::solve_triangular_blocked(a, b, nrhs, upper, unit, x);
    else
        core::detail::solve_triangular_cpu(a, b, nrhs, upper, unit, x);
}

} // namespace metal_linalg
