# Writes swift/CMetalLinalg/embedded_shaders.c, the Swift package's copy of
# the compiled shaders, from the metallibs committed under shaders/prebuilt/.
# The Swift package cannot run CMake, so it compiles this file instead; plain
# byte arrays rather than C23's #embed, which the Xcode on macOS 14 lacks.
#
#   cmake -DROOT=<repository root> [-DOUTPUT=<file.c>] -P EmbedSwiftShaders.cmake
#
# `update_prebuilt_shaders` runs it; the "Older macOS" workflow checks the
# committed file matches. The order is that of src/shaders.h.
if (NOT ROOT)
    message(FATAL_ERROR "EmbedSwiftShaders.cmake needs ROOT")
endif ()
if (NOT OUTPUT)
    set(OUTPUT "${ROOT}/swift/CMetalLinalg/embedded_shaders.c")
endif ()
set(_names QR_Unblocked QR_Streaming_AMX_Reduced QR_Streaming_AMX_Complete
           Eigh_Jacobi Eigh_BlockJacobi Eigh_Tridiag Eigh_QL Svd_Jacobi Svd_BlockJacobi Svd_Bidiag)
set(_out "// Generated by cmake/EmbedSwiftShaders.cmake from shaders/prebuilt/; do not edit.
// The compiled shaders for the Swift package, which cannot run CMake's
// embedding step: refresh with `cmake --build build --target update_prebuilt_shaders`.
// Defines the symbols src/shaders.h declares.

#include <stddef.h>
")
foreach (_n IN LISTS _names)
    set(_in "${ROOT}/shaders/prebuilt/${_n}.metallib")
    if (NOT EXISTS "${_in}")
        message(FATAL_ERROR "EmbedSwiftShaders.cmake: missing ${_in}")
    endif ()
    file(READ "${_in}" _hex HEX)
    string(LENGTH "${_hex}" _hex_len)
    math(EXPR _len "${_hex_len} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" _bytes "${_bytes}")
    string(APPEND _out "
const unsigned char metal_linalg_${_n}_metallib[] = {
${_bytes}
};
const size_t metal_linalg_${_n}_metallib_len = ${_len};
")
endforeach ()
file(WRITE "${OUTPUT}" "${_out}")
