# Turns a compiled Metal library into a C++ source that carries its bytes, so
# that the shaders travel inside libmetal_linalg and nothing has to be found
# on disk at run time.
#
#   cmake -DINPUT=<file.metallib> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -P EmbedMetallib.cmake
#
# defines `extern "C" const unsigned char <name>[]` and `<name>_len`.
if (NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
    message(FATAL_ERROR "EmbedMetallib.cmake needs INPUT, OUTPUT and SYMBOL")
endif ()
file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hex_len)
math(EXPR _len "${_hex_len} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" _bytes "${_bytes}")
get_filename_component(_name "${INPUT}" NAME)
file(WRITE "${OUTPUT}"
"// Generated by cmake/EmbedMetallib.cmake from ${_name}; do not edit.
#include <cstddef>
extern \"C\" const unsigned char ${SYMBOL}[] = {
${_bytes}
};
extern \"C\" const size_t ${SYMBOL}_len = ${_len};
")
