#!/usr/bin/env python3
"""Combine every run submitted for one device into its rows for kTuned[].

    python3 tuning/combine.py docs/results/apple-m5-pro-20gpu

For each decomposition it uses every submission whose measurements of it are
trustworthy and from the current measurement epoch, skips the rest (smoke
tests, interrupted runs, untrustworthy results, older epochs) and says why,
re-runs the analysis over all of them together, and writes
docs/results/<device>/combined/: one report per decomposition and a
summary.md. No GPU is needed. How runs combine is described in
tuning/submissions.py.

tuning/generate_tables.py does this for every device and writes the rows into
the library; this script is the same step for one device, to look at.
"""

import argparse
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import submissions as sub   # noqa: E402

OPS = [("qr", "tune_qr.py", "src/qr.mm"), ("eigh", "tune_eigh.py", "src/eigh.mm"),
       ("svd", "tune_svd.py", "src/svd.mm")]


def load_submissions(device_dir):
    """[(id, submission.json)] for every submission of one device."""
    out = []
    for name in sorted(os.listdir(device_dir)):
        path = os.path.join(device_dir, name, "submission.json")
        if name != "combined" and os.path.exists(path):
            out.append((name, json.load(open(path))))
    return out


def eligible(subs, op, device_dir):
    """(used, skipped) for one decomposition: used as [(id, raw.csv)],
    skipped as ["id (reason)"]."""
    used, skipped = [], []
    for name, info in subs:
        r = info.get("results", {}).get(op)
        raw = os.path.join(device_dir, name, op, "raw.csv")
        if not r or not os.path.exists(raw):
            continue
        if info.get("quick"):
            skipped.append(f"{name} (smoke test)")
        elif info.get("status") == "running":
            skipped.append(f"{name} (interrupted)")
        elif info.get("epoch", 0) < sub.EPOCH:
            skipped.append(f"{name} (measured with older kernels, epoch {info.get('epoch', 0)})")
        elif not r.get("trustworthy"):
            skipped.append(f"{name} ({r.get('why') or 'not trustworthy'})")
        else:
            used.append((name, raw))
    return used, skipped


def combine_device(device_dir):
    """Combines one device's runs. Returns {"device", "subs", "ops": {op: {"row",
    "used", "skipped"}}} and writes <device_dir>/combined/. Paths handed to the
    harnesses are relative to the repository, so the output does not depend
    on where the repository is."""
    device_dir = os.path.relpath(os.path.abspath(device_dir), ROOT)
    subs = load_submissions(os.path.join(ROOT, device_dir))
    if not subs:
        return None
    out_root = os.path.join(device_dir, "combined")
    result = {"device": subs[0][1]["device"], "subs": [n for n, _ in subs], "ops": {}}
    for op, harness, target in OPS:
        used, skipped = eligible(subs, op, device_dir)
        entry = {"row": None, "used": [n for n, _ in used], "skipped": skipped, "target": target}
        if used:
            out = os.path.join(out_root, op)
            cmd = [sys.executable, os.path.join("tuning", harness), "--reanalyse",
                   *[raw for _, raw in used], "--out", out]
            r = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
            if r.returncode != 0:
                raise RuntimeError(f"{harness} failed for {device_dir}:\n{r.stdout}{r.stderr}")
            res = json.load(open(os.path.join(ROOT, out, "results.json")))
            entry["row"] = (res.get("ktuned_entry") or res.get("tuned_row")).rstrip(",").strip()
        result["ops"][op] = entry

    lines = []
    for op, e in result["ops"].items():
        skip = f"; skipped {', '.join(e['skipped'])}" if e["skipped"] else ""
        if e["row"]:
            n = len(e["used"])
            lines.append(f"- **{op}** from {n} run{'s' if n > 1 else ''} ({', '.join(e['used'])}){skip}: "
                         f"`{e['row']}` in `{e['target']}` ([report]({op}/report.md))")
        else:
            lines.append(f"- **{op}**: no usable runs{skip}")
    d = result["device"]
    os.makedirs(os.path.join(ROOT, out_root), exist_ok=True)
    with open(os.path.join(ROOT, out_root, "summary.md"), "w") as fh:
        fh.write(f"# {d['name']}, {d['gpu_cores']} GPU cores — combined\n\n"
                 f"Generated by `tuning/generate_tables.py` from {len(subs)} "
                 f"run{'s' if len(subs) > 1 else ''}; do not edit.\n\n" + "\n".join(lines) + "\n")
    return result


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("device_dir", help="docs/results/<device>")
    args = ap.parse_args()
    res = combine_device(args.device_dir)
    if res is None:
        sys.exit(f"no submissions in {args.device_dir}")
    d = res["device"]
    print(f"{d['name']}, {d['gpu_cores']} GPU cores: {len(res['subs'])} runs")
    for op, e in res["ops"].items():
        print(f"  {e['target']:12s} {e['row'] or '(no usable runs)'}")
        for s in e["skipped"]:
            print(f"      skipped {s}")


if __name__ == "__main__":
    main()
