#!/usr/bin/env python3
"""Fit every device's rows from every submitted run and write them into the
library.

    python3 tuning/generate_tables.py            # regenerate
    python3 tuning/generate_tables.py --check    # fail if anything is out of date

For each device under docs/results/, combines its runs (tuning/combine.py)
and writes the rows into src/tuned/qr.inc, eigh.inc, svd.inc, cholesky.inc,
lu.inc and trsm.inc, which the kTuned[] tables in src/qr.mm, src/eigh.mm,
src/svd.mm, src/cholesky.mm, src/lu.mm and src/trsm.mm include. From the
devices measured at the current kernels it refits the estimated rows for the
Macs nobody has measured (tuning/estimate.py) into src/tuned/*_estimated.inc,
and writes tuning/chip_specs.py into src/tuned/chips.inc. It also
rewrites the tables of measured devices in README.md and docs/tuning.md
(between the marker comments there), so they never fall behind the results. The GitHub
Action in .github/workflows/tuned-policies.yml runs this on every pull request
that adds results (to show what would change) and after every merge (to apply
it). Needs Python 3.8+ and nothing else: no GPU, no build.
"""

import argparse
import json
import os
import shutil
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import chip_specs         # noqa: E402
import combine            # noqa: E402
import estimate           # noqa: E402
import measurements_page  # noqa: E402

RESULTS = os.path.join("docs", "results")
TABLES = os.path.join("src", "tuned")
DOCS = ["README.md", os.path.join("docs", "tuning.md")]   # each holds one generated table
PAGE = os.path.join("docs", "measurements.md")           # generated whole

# How a row tells the library its measurements are not current (src/calibration.h).
MARKER = {"stale": "kCalibrationStale", "incomplete": "kCalibrationIncomplete"}
BEGIN = "<!-- generated by tuning/generate_tables.py from docs/results/; do not edit -->"
END = "<!-- end of generated table -->"


def devices():
    base = os.path.join(ROOT, RESULTS)
    return sorted(d for d in os.listdir(base) if os.path.isdir(os.path.join(base, d)))


def generate():
    """{op: include-file text}, and the per-device results for the summary."""
    per_device = {}
    for d in devices():
        res = combine.combine_device(os.path.join(ROOT, RESULTS, d))
        if res is not None:
            per_device[d] = res
    files = {}
    for op, _, _ in combine.OPS:
        lines = ["// Generated by tuning/generate_tables.py from docs/results/; do not edit.",
                 "// One row per device with usable runs; see docs/tuning.md. A last field",
                 "// kCalibrationStale / kCalibrationIncomplete says the runs are not current",
                 "// (tuning/kernels.py, docs/measurements.md)."]
        for d, res in per_device.items():
            e = res["ops"][op]
            if e["row"]:
                n = len(e["used"])
                st = e["status"]
                lines.append(f"// {d}: {n} run{'s' if n > 1 else ''} ({', '.join(e['used'])}), {st['state']}"
                             + (f" (kernel version {st['epoch']}, current {st['current_epoch']})"
                                if st["state"] == "stale" else "")
                             + (f" (never timed {', '.join(st['missing'])})" if st["state"] == "incomplete" else ""))
                row = e["row"].rstrip()
                if st["state"] in MARKER:
                    row = row[:row.rindex("}")].rstrip() + f",   {MARKER[st['state']]}}}"
                lines.append(row + ",")
        files[op] = "\n".join(lines) + "\n"
    for name, text in estimate.generate(anchors(per_device)).items():
        files[name if name == "chips" else f"{name}_estimated"] = text
    return files, per_device


def anchors(per_device):
    """{op: [(chip_specs row, [raw.csv paths])]}: the devices whose runs for
    that decomposition are current, and which tuning/chip_specs.py lists, as
    tuning/estimate.py takes them."""
    out = {op: [] for op, _, _ in combine.OPS}
    for d, res in per_device.items():
        dev = res["device"]
        for op, _, _ in combine.OPS:
            e = res["ops"][op]
            if not e["row"] or e["status"]["state"] != "current":
                continue
            sub = json.load(open(os.path.join(ROOT, RESULTS, d, e["used"][0], "submission.json")))
            spec = chip_specs.find(dev["name"], dev["gpu_cores"], (sub.get("cpu") or {}).get("cores"))
            if spec:
                out[op].append((spec, [os.path.join(RESULTS, d, n, op, "raw.csv") for n in e["used"]]))
    return out


def doc_table(doc, per_device):
    """The table of measured devices that `doc` shows."""
    ops = [op for op, _, _ in combine.OPS]
    def measured(res, op, no):
        e = res["ops"][op]
        if not e["row"]:
            if any("before 2.9.0" in s for s in e["skipped"]):
                return "out of date" if no == "—" else f"{no} (out of date)"
            return no
        return {"current": "measured", "incomplete": "measured (incomplete)",
                "stale": "measured (stale)"}[e["status"]["state"]]
    if doc == "README.md":
        L = ["| device | QR | eigh | SVD | Cholesky | LU | triangular solve |", "|---|---|---|---|---|---|---|"]
        for res in per_device.values():
            dev = res["device"]
            L.append(f"| {dev['name']}, {dev['gpu_cores']} GPU cores | "
                     + " | ".join(measured(res, op, "estimated") for op in ops) + " |")
        L.append("| anything else | estimated | estimated | estimated | estimated | estimated | estimated |")
        L.append("")
        L.append("Every chip, and what is current: [the measurements page](https://c0rmac.github.io/metal-linalg/docs/measurements).")
    else:
        L = ["| Mac | GPU cores | QR | eigh | SVD | Cholesky | LU | triangular solve | runs |",
             "|---|---|---|---|---|---|---|---|---|"]
        for res in per_device.values():
            dev = res["device"]
            L.append(f"| {dev['name']} | {dev['gpu_cores']} | "
                     + " | ".join(measured(res, op, "—") for op in ops) + f" | {len(res['subs'])} |")
    return "\n".join(L)


def write_doc_table(doc, per_device):
    path = os.path.join(ROOT, doc)
    s = open(path).read()
    if BEGIN not in s or END not in s:
        sys.exit(f"generate_tables.py: {doc} has lost its generated-table markers")
    head, rest = s.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    open(path, "w").write(head + BEGIN + "\n" + doc_table(doc, per_device) + "\n" + END + tail)


def summary(per_device):
    L = ["| device | runs | QR | eigh | SVD | Cholesky | LU | triangular solve |", "|---|---|---|---|---|---|---|---|"]
    for d, res in per_device.items():
        cells = []
        for op, _, _ in combine.OPS:
            e = res["ops"][op]
            cells.append(f"`{e['row']}`" if e["row"] else "—")
        L.append(f"| {d} | {len(res['subs'])} | " + " | ".join(cells) + " |")
    skipped = [f"- {d} {op}: skipped {s}" for d, res in per_device.items()
               for op, e in res["ops"].items() for s in e["skipped"]]
    runs = []
    for d, res in per_device.items():
        runs += ["", f"### {d}: runs", "", res["runs_table"].rstrip("\n")]
    return "\n".join(L + ([""] + skipped if skipped else []) + runs) + "\n"


def snapshot(paths):
    """Contents of every file under `paths`, relative to the repository."""
    out = {}
    for p in paths:
        full = os.path.join(ROOT, p)
        if os.path.isfile(full):
            out[p] = open(full, "rb").read()
        for dirpath, _, names in os.walk(full):
            for n in names:
                f = os.path.join(dirpath, n)
                out[os.path.relpath(f, ROOT)] = open(f, "rb").read()
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="change nothing; exit 1 if the tables or combined reports are out of date")
    ap.add_argument("--summary", metavar="FILE", help="append a Markdown summary to FILE")
    args = ap.parse_args()

    combined = [os.path.join(RESULTS, d, "combined") for d in devices()]
    generated = combined + [TABLES] + DOCS + [PAGE]
    before = snapshot(generated) if args.check else None
    backup = tempfile.mkdtemp() if args.check else None
    if args.check:   # generate into the tree, compare, then put everything back
        for p in generated:
            src, dst = os.path.join(ROOT, p), os.path.join(backup, p)
            if os.path.isdir(src):
                shutil.copytree(src, dst)
            elif os.path.isfile(src):
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copy2(src, dst)

    try:
        files, per_device = generate()
        os.makedirs(os.path.join(ROOT, TABLES), exist_ok=True)
        for op, text in files.items():
            open(os.path.join(ROOT, TABLES, f"{op}.inc"), "w").write(text)
        for doc in DOCS:
            write_doc_table(doc, per_device)
        open(os.path.join(ROOT, PAGE), "w").write(measurements_page.render(per_device))
        text = summary(per_device)
        print(text, end="")
        if args.summary:
            open(args.summary, "a").write("## Tuned policies\n\n" + text)
        if args.check:
            after = snapshot(generated)
            stale = sorted(k for k in set(before) | set(after) if before.get(k) != after.get(k))
            if stale:
                print("out of date: " + ", ".join(stale), file=sys.stderr)
                return 1
        return 0
    finally:
        if args.check:
            for p in generated:
                full, saved = os.path.join(ROOT, p), os.path.join(backup, p)
                if os.path.isdir(full):
                    shutil.rmtree(full)
                if os.path.isdir(saved):
                    shutil.copytree(saved, full)
                elif os.path.isfile(saved):
                    shutil.copy2(saved, full)
            shutil.rmtree(backup)


if __name__ == "__main__":
    sys.exit(main())
