#!/usr/bin/env python3
"""Fit every device's rows from every submitted run and write them into the
library.

    python3 tuning/generate_tables.py            # regenerate
    python3 tuning/generate_tables.py --check    # fail if anything is out of date

For each device under docs/results/, combines its runs (tuning/combine.py)
and writes the rows into src/tuned/qr.inc, eigh.inc and svd.inc, which the
kTuned[] tables in src/qr.mm, src/eigh.mm and src/svd.mm include. The GitHub
Action in .github/workflows/tuned-policies.yml runs this on every pull request
that adds results (to show what would change) and after every merge (to apply
it). Needs Python 3.8+ and nothing else: no GPU, no build.
"""

import argparse
import os
import shutil
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import combine   # noqa: E402

RESULTS = os.path.join("docs", "results")
TABLES = os.path.join("src", "tuned")


def devices():
    base = os.path.join(ROOT, RESULTS)
    return sorted(d for d in os.listdir(base) if os.path.isdir(os.path.join(base, d)))


def generate():
    """{op: include-file text}, and the per-device results for the summary."""
    per_device = {}
    for d in devices():
        res = combine.combine_device(os.path.join(ROOT, RESULTS, d))
        if res is not None:
            per_device[d] = res
    files = {}
    for op, _, _ in combine.OPS:
        lines = ["// Generated by tuning/generate_tables.py from docs/results/; do not edit.",
                 "// One row per device with usable runs; see docs/tuning.md."]
        for d, res in per_device.items():
            e = res["ops"][op]
            if e["row"]:
                n = len(e["used"])
                lines.append(f"// {d}: {n} run{'s' if n > 1 else ''} ({', '.join(e['used'])})")
                lines.append(e["row"] + ",")
        files[op] = "\n".join(lines) + "\n"
    return files, per_device


def summary(per_device):
    L = ["| device | runs | QR | eigh | SVD |", "|---|---|---|---|---|"]
    for d, res in per_device.items():
        cells = []
        for op, _, _ in combine.OPS:
            e = res["ops"][op]
            cells.append(f"`{e['row']}`" if e["row"] else "—")
        L.append(f"| {d} | {len(res['subs'])} | " + " | ".join(cells) + " |")
    skipped = [f"- {d} {op}: skipped {s}" for d, res in per_device.items()
               for op, e in res["ops"].items() for s in e["skipped"]]
    runs = []
    for d, res in per_device.items():
        runs += ["", f"### {d}: runs", "", res["runs_table"].rstrip("\n")]
    return "\n".join(L + ([""] + skipped if skipped else []) + runs) + "\n"


def snapshot(paths):
    """Contents of every file under `paths`, relative to the repository."""
    out = {}
    for p in paths:
        full = os.path.join(ROOT, p)
        if os.path.isfile(full):
            out[p] = open(full, "rb").read()
        for dirpath, _, names in os.walk(full):
            for n in names:
                f = os.path.join(dirpath, n)
                out[os.path.relpath(f, ROOT)] = open(f, "rb").read()
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="change nothing; exit 1 if the tables or combined reports are out of date")
    ap.add_argument("--summary", metavar="FILE", help="append a Markdown summary to FILE")
    args = ap.parse_args()

    combined = [os.path.join(RESULTS, d, "combined") for d in devices()]
    before = snapshot(combined + [TABLES]) if args.check else None
    backup = tempfile.mkdtemp() if args.check else None
    if args.check:   # generate into the tree, compare, then put everything back
        for p in combined + [TABLES]:
            if os.path.exists(os.path.join(ROOT, p)):
                shutil.copytree(os.path.join(ROOT, p), os.path.join(backup, p))

    try:
        files, per_device = generate()
        os.makedirs(os.path.join(ROOT, TABLES), exist_ok=True)
        for op, text in files.items():
            open(os.path.join(ROOT, TABLES, f"{op}.inc"), "w").write(text)
        text = summary(per_device)
        print(text, end="")
        if args.summary:
            open(args.summary, "a").write("## Tuned policies\n\n" + text)
        if args.check:
            after = snapshot(combined + [TABLES])
            stale = sorted(k for k in set(before) | set(after) if before.get(k) != after.get(k))
            if stale:
                print("out of date: " + ", ".join(stale), file=sys.stderr)
                return 1
        return 0
    finally:
        if args.check:
            for p in combined + [TABLES]:
                full = os.path.join(ROOT, p)
                if os.path.exists(full):
                    shutil.rmtree(full)
                if os.path.exists(os.path.join(backup, p)):
                    shutil.copytree(os.path.join(backup, p), full)
            shutil.rmtree(backup)


if __name__ == "__main__":
    sys.exit(main())
