"""Renders docs/measurements.md: every Apple Silicon chip, and how current its
measurements are, decomposition by decomposition. Called by
tuning/generate_tables.py; nothing here measures anything.

The page is Markdown with HTML tables, so GitHub Pages shows the colours; the
symbols in each cell carry the same information where styles are stripped.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import chips     # noqa: E402
import kernels   # noqa: E402

OPS = [("qr", "QR"), ("eigh", "eigh"), ("svd", "SVD"), ("cholesky", "Cholesky"), ("lu", "LU"), ("trsm", "triangular solve")]
REPO = "https://github.com/c0rmac/metal-linalg"

STATES = {
    #              symbol, background, label
    "current":    ("🟢", "#dcfce7", "current"),
    "incomplete": ("🟡", "#fef9c3", "incomplete"),
    "stale":      ("🟠", "#ffedd5", "stale"),
    "none":       ("🔴", "#fee2e2", "not measured"),
}


def _esc(s):
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _cell(state, lines):
    sym, bg, label = STATES[state]
    body = "<br>".join([f"{sym} <b>{label}</b>"] + [_esc(l) for l in lines])
    return f'<td style="background:{bg};color:#1c1917">{body}</td>'


def _op_cell(res, op):
    if res is None:
        return _cell("none", ["estimated"])
    e = res["ops"][op]
    st = e["status"]
    if not e["row"]:
        old = any("before 2.9.0" in s for s in e["skipped"])
        return _cell("none", ["estimated"] + (["its runs predate 2.9.0: out of date"] if old else []))
    info = res["sub_info"]
    used = e["used"]
    dates = sorted(info[n]["date"] for n in used if info[n].get("date"))
    versions = sorted({info[n]["library_version"] for n in used if info[n].get("library_version")})
    lines = [f"{len(used)} run{'s' if len(used) > 1 else ''}, "
             + (f"latest {dates[-1]}" if dates else "date not recorded")]
    if versions:
        lines.append("measured with " + ", ".join(versions))
    if st["state"] == "stale":
        lines.append(f"kernel version {st['epoch']}, now {st['current_epoch']}: still used")
    if st["state"] == "incomplete":
        missing = sorted({kernels.added(op, b) for b in st["missing"]})
        lines.append("never timed " + "; ".join(missing) + ": off until remeasured")
    return _cell(st["state"], lines)


def _rows(per_device):
    """[(generation, chip, cores, res or None)], every listed chip and every
    measured one, grouped by generation."""
    measured = {(r["device"]["name"], r["device"]["gpu_cores"]): r for r in per_device.values()}
    out, seen = [], set()
    gens = [g for g, _ in chips.GENERATIONS]
    for g in sorted({chips.generation_of(n) for n, _ in measured if chips.generation_of(n)} - set(gens)):
        gens.append(g)   # a generation newer than the list
    listed = dict(chips.GENERATIONS)
    for g in gens:
        entries = [(n, list(c)) for n, c in listed.get(g, [])]
        for (n, c) in measured:   # measured chips the list lacks
            if chips.generation_of(n) == g:
                for e in entries:
                    if e[0] == n:
                        if c not in e[1]:
                            e[1].append(c)
                        break
                else:
                    entries.append((n, [c]))
        for n, cores in entries:
            for c in sorted(cores):
                out.append((g, n, c, measured.get((n, c))))
                seen.add((n, c))
    for (n, c), r in sorted(measured.items()):
        if (n, c) not in seen:
            out.append(("other", n, c, r))
    return out


def render(per_device):
    rows = _rows(per_device)
    counts = {s: 0 for s in STATES}
    for _, _, _, r in rows:
        for op, _ in OPS:
            counts[r["ops"][op]["status"]["state"] if r and r["ops"][op]["row"] else "none"] += 1
    L = ["# Measurements", "",
         "<!-- generated by tuning/generate_tables.py from docs/results/; do not edit -->", "",
         "metal-linalg routes every call by measurements made on each kind of Mac. This page "
         "lists every Apple Silicon chip and how current its measurements are, for each "
         "decomposition. It is regenerated from the submitted runs on every merge.", "",
         "| | state | what it means |", "|---|---|---|",
         f"| {STATES['current'][0]} | **current** | measured at the current kernels, every backend timed |",
         f"| {STATES['incomplete'][0]} | **incomplete** | still valid, but a newer backend was never timed on this "
         "chip, so it stays off there |",
         f"| {STATES['stale'][0]} | **stale** | measured on older kernels; still used, as the best "
         "available, until remeasured (runs from before 2.9.0, when the CPU path ran on one core, are "
         "out of date and not used: such a chip is estimated) |",
         f"| {STATES['none'][0]} | **not measured** | estimated from a measured Mac and published benchmarks "
         "([how](https://github.com/c0rmac/metal-linalg/blob/main/docs/studies/estimated-policies.md)): "
         "conservative, so it misses some GPU wins |", "",
         f"**Have one of these Macs?** One command measures it, in about an hour and a half, and a pull request "
         f"submits it: [how to contribute]({REPO}/blob/main/CONTRIBUTING.md). Every run improves the "
         f"library for everyone with that chip; the library prints a notice on chips that need one.", "",
         f"{counts['current']} current, {counts['incomplete']} incomplete, {counts['stale']} stale and "
         f"{counts['none']} not measured, over {len(rows)} chip configurations and 3 decompositions.", ""]

    L += ["## By chip", "",
          "<table>",
          "<tr><th>chip</th><th>GPU cores</th>" + "".join(f"<th>{lab}</th>" for _, lab in OPS) + "</tr>"]
    last = None
    for g, name, cores, r in rows:
        if g != last:
            L.append(f'<tr><th colspan="{2 + len(OPS)}" style="text-align:left">{_esc(g)}</th></tr>')
            last = g
        L.append(f"<tr><td>{_esc(name)}</td><td>{cores}</td>" + "".join(_op_cell(r, op) for op, _ in OPS) + "</tr>")
    L += ["</table>", ""]

    L += ["## Submitted runs", "",
          "Every run under [`docs/results/`](https://github.com/c0rmac/metal-linalg/tree/main/docs/results), "
          "and what each decomposition's measurements in it are used for.", "",
          "| run | chip | GPU cores | date | machine | macOS | library | " +
          " | ".join(lab for _, lab in OPS) + " |",
          "|---|---|---|---|---|---|---|" + "---|" * len(OPS)]
    for r in sorted(per_device.values(), key=lambda r: (r["device"]["name"], r["device"]["gpu_cores"])):
        dev = r["device"]
        for n in sorted(r["subs"], reverse=True):
            i = r["sub_info"][n]
            cells = []
            for op, _ in OPS:
                e = r["ops"][op]
                if n in e["used"]:
                    cells.append("used" + (" (stale)" if e["status"]["state"] == "stale" else ""))
                elif op in i.get("measured", []):
                    why = next((s.split(" (", 1)[1].rstrip(")") for s in e["skipped"] if s.startswith(n + " ")),
                               "not used")
                    cells.append(_esc(why))
                else:
                    cells.append("—")
            L.append(f"| {n} | {_esc(dev['name'])} | {dev['gpu_cores']} | {i.get('date') or 'not recorded'} | "
                     f"{_esc(i.get('machine') or '?')} | {i.get('macos') or '?'} | "
                     f"{i.get('library_version') or 'before 2.6'} | " + " | ".join(cells) + " |")
    L.append("")

    L += ["## Kernel versions", "",
          "A decomposition's measurements go stale only when something they time changes: its "
          "kernels, their launch parameters, its CPU path, or what it calls. Releases that change "
          "nothing of the kind keep every measurement current. Each change that does bumps that "
          "decomposition's kernel version ([`tuning/kernels.py`]"
          "(https://github.com/c0rmac/metal-linalg/blob/main/tuning/kernels.py)):", "",
          "| decomposition | version | since | date | why |", "|---|---|---|---|---|"]
    for op, ep, ver, date, why in kernels.HISTORY:
        cur = " (current)" if kernels.KERNEL_EPOCHS[op] == ep else ""
        L.append(f"| {dict(OPS)[op]} | {ep}{cur} | {ver} | {date} | {_esc(why)} |")
    L.append("")
    return "\n".join(L)
